In [1]:
%pylab inline
from __future__ import print_function
from astropy.io import fits
import os
import numpy as np
import glob
import matplotlib.pyplot as plt
from astropy.wcs import WCS
%matplotlib inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
datadir = "../SDSS_spectra/spect_18r20/"
fitsfile = "spec-0378-52146-0223.fits"
hdulist = fits.open(os.path.join(datadir, fitsfile))

In [3]:
hdulist.info()

Filename: ../SDSS_spectra/spect_18r20/spec-0378-52146-0223.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     139   ()      
  1  COADD         1 BinTableHDU     26   3830R x 8C   [E, E, E, J, J, E, E, E]   
  2  SPECOBJ       1 BinTableHDU    262   1R x 126C   [6A, 4A, 16A, 23A, 16A, 8A, E, E, E, J, E, E, J, B, B, B, B, B, B, J, 22A, 19A, 19A, 22A, 19A, I, 3A, 3A, 1A, J, D, D, D, E, E, 19A, 8A, J, J, J, J, K, K, J, J, J, J, J, J, K, K, K, K, I, J, J, J, J, 5J, D, D, 6A, 21A, E, E, E, J, E, 24A, 10J, J, 10E, E, E, E, E, E, E, J, E, E, E, J, E, 5E, E, 10E, 10E, 10E, 5E, 5E, 5E, 5E, 5E, J, J, E, E, E, E, E, E, 25A, 21A, 10A, E, E, E, E, E, E, E, E, J, E, E, J, 1A, 1A, E, E, J, J, 1A, 5E, 5E]   
  3  SPZLINE       1 BinTableHDU     48   29R x 19C   [J, J, J, 13A, D, E, E, E, E, E, E, E, E, E, E, J, J, E, E]   


In [4]:
hdulist[0].header

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                    8 / array data type                                
NAXIS   =                    0 / number of array dimensions                     
EXTEND  =                    T                                                  
TAI     =        4505441894.76 / 1st row - Number of seconds since Nov 17 1858  
RA      =            341.40996 / 1st row - Right ascension of telescope boresigh
DEC     =           -0.037734  / 1st row - Declination of telescope boresight (d
EQUINOX =              2000.00 /                                                
RADECSYS= 'FK5     '           /                                                
TAIHMS  = '07:20:16.02'        / 1st row - TAI time (HH:MM:SS.SS) (TAI-UT = appr
TIMESYS = 'tai     '           / TAI, not UTC                                   
MJD     =                52146 / MJD of observation                             
MJDLIST = '52146   '        

In [5]:
data = hdulist[1].data
data

FITS_rec([(-2.0162725, 3.5808, 0.10477413, 0, 1048576, 1.1833422, 7.1584635, 5.444991 ),
          ( 7.2265935, 3.5809, 0.09253734, 0,       0, 1.1831326, 7.1556764, 5.446005 ),
          ( 8.172218 , 3.581 , 0.09371056, 0,       0, 1.1829675, 7.3476486, 5.549213 ),
          ...,
          ( 3.4545326, 3.9635, 1.1675137 , 0,       0, 0.7167422, 4.0312552, 3.3565245),
          ( 2.7277253, 3.9636, 1.0761456 , 0,       0, 0.7168129, 4.3179293, 3.3574529),
          ( 4.1882772, 3.9637, 1.0384908 , 0,       0, 0.7168842, 4.322691 , 3.3583813)],
         dtype=(numpy.record, [('flux', '>f4'), ('loglam', '>f4'), ('ivar', '>f4'), ('and_mask', '>i4'), ('or_mask', '>i4'), ('wdisp', '>f4'), ('sky', '>f4'), ('model', '>f4')]))

In [6]:
data.field("flux")

array([-2.0162725,  7.2265935,  8.172218 , ...,  3.4545326,  2.7277253,
        4.1882772], dtype=float32)

In [7]:
data.field("loglam")

array([3.5808, 3.5809, 3.581 , ..., 3.9635, 3.9636, 3.9637], dtype=float32)

In [8]:
hdulist[0].header["BUNIT"]

'1E-17 erg/cm^2/s/Ang'

In [9]:
1E-17 * data.field("flux")

array([-2.0162724e-17,  7.2265933e-17,  8.1722182e-17, ...,
        3.4545326e-17,  2.7277252e-17,  4.1882772e-17], dtype=float32)

In [10]:
10**data.field("loglam")

array([3808.9043, 3809.7805, 3810.659 , ..., 9193.905 , 9196.0205,
       9198.141 ], dtype=float32)

In [11]:
print(hdulist[0].header["PLUG_RA"],
hdulist[0].header["PLUG_DEC"])

340.96744 -0.38333539


In [12]:
for i in 10**data.field("loglam"):
    print(i)

3808.9043
3809.7805
3810.659
3811.5356
3812.4126
3813.2917
3814.169
3815.0483
3815.926
3816.806
3817.684
3818.5623
3819.4429
3820.3215
3821.2024
3822.0815
3822.963
3823.8423
3824.724
3825.604
3826.4841
3827.3665
3828.2468
3829.1296
3830.0105
3830.8938
3831.7751
3832.6565
3833.5403
3834.4224
3835.3064
3836.1887
3837.0735
3837.956
3838.839
3839.7244
3840.6077
3841.4932
3842.377
3843.263
3844.1472
3845.0315
3845.9182
3846.803
3847.69
3848.5752
3849.4626
3850.3481
3851.234
3852.122
3853.0083
3853.8967
3854.7832
3855.672
3856.559
3857.4463
3858.336
3859.2234
3860.1135
3861.0015
3861.8918
3862.7803
3863.6687
3864.5598
3865.4487
3866.34
3867.2297
3868.1213
3869.0112
3869.9014
3870.7937
3871.684
3872.577
3873.4678
3874.361
3875.2524
3876.1438
3877.0376
3877.9297
3878.8237
3879.716
3880.6108
3881.5037
3882.3965
3883.2917
3884.185
3885.0808
3885.9746
3886.8706
3887.765
3888.6592
3889.556
3890.4507
3891.348
3892.243
3893.1406
3894.0361
3894.934
3895.83
3896.7263
3897.625
3898.5215
3899.4207
3900.

6631.32
6632.8486
6634.3745
6635.901
6637.431
6638.958
6640.489
6642.0166
6643.5483
6645.0767
6646.6055
6648.138
6649.6675
6651.2007
6652.731
6654.265
6655.796
6657.327
6658.8623
6660.394
6661.9297
6663.4624
6664.999
6666.532
6668.066
6669.6035
6671.1377
6672.6763
6674.2114
6675.7505
6677.286
6678.8257
6680.3623
6681.899
6683.44
6684.9775
6686.519
6688.057
6689.5996
6691.138
6692.6777
6694.221
6695.7607
6697.305
6698.8457
6700.3906
6701.9316
6703.4736
6705.0195
6706.562
6708.1084
6709.652
6711.1987
6712.7427
6714.287
6715.8354
6717.3804
6718.929
6720.475
6722.025
6723.5713
6725.1177
6726.6685
6728.2163
6729.7676
6731.316
6732.868
6734.417
6735.9663
6737.5195
6739.0693
6740.6235
6742.1743
6743.729
6745.2803
6746.832
6748.3877
6749.9404
6751.4966
6753.05
6754.607
6756.161
6757.7153
6759.2734
6760.8286
6762.3877
6763.9434
6765.503
6767.0596
6768.616
6770.1772
6771.7344
6773.296
6774.854
6776.4165
6777.9756
6779.5347
6781.098
6782.658
6784.222
6785.7827
6787.3477
6788.909
6790.4707
6792.03

In [13]:
datadir1 = "../Lamost_spectra/spect_16r18/"
fitsfile1 = "spec-57751-KP114249S033242B02_sp12-186.fits"
hdu = fits.open(os.path.join(datadir1, fitsfile1))

In [17]:
hdu[0].header

SIMPLE  =                    T /Primary Header created by MWRFITS v1.11b        
BITPIX  =                  -32 /                                                
NAXIS   =                    2 / Number of array dimensions                     
NAXIS1  =                 3906 /                                                
NAXIS2  =                    5 /                                                
EXTEND  =                    T /                                                
                                                                                
COMMENT --------FILE INFORMATION                                                
FILENAME= 'spec-57751-KP114249S033242B02_sp12-186.fits' /                       
OBSID   =            502212186 / Unique number ID of this spectrum              
AUTHOR  = 'LAMOST Pipeline'    / Who compiled the information                   
DATA_V  = 'LAMOST DR5'         / Data release version                           
EXTEN0  = 'Flux, Inverse, Wa

In [14]:
ra = hdu[0].header["RA"]
dec = hdu[0].header["DEC"]

In [15]:
print(ra, dec)

177.075783 -1.63993
